[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 180, lines = 40 }
decorations = "transparent"
opacity = 0.25
blur = true
startup_mode = "Windowed"
padding = { x = 10, y = 30 }
dynamic_padding = false
option_as_alt = "Both"


[font]
normal = { family = "ComicCodeLigatures Nerd Font", style = "Regular" }
italic = { family = "ComicCodeLigatures Nerd Font", style = "Italic" }
bold = { family = "ComicCodeLigatures Nerd Font", style = "Medium" }
bold_italic = { family = "ComicCodeLigatures Nerd Font", style = "Medium Italic" }
size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Command", chars = "\u001BF" },
  { key = "Left", mods = "Command", chars = "\u001BB" },
]
